repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.0 # Use the latest version
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, snowflake] # Change to your dialect
      - id: sqlfluff-fix
        args: [--dialect, snowflake]
